import Head from "next/head";
import Image from "next/image";
import { Geist, Geist_Mono } from "next/font/google";
import styles from "@/styles/Home.module.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Mail.app</title>
        <meta name="description" content="Generated by Mohamed Jamal" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        className={`${styles.page} ${geistSans.variable} ${geistMono.variable}`}
      >
        <main>
          <center>
            <div style={{ marginBottom: "10px" }}>
              <h2 >Mohamed Jamal M</h2>
              <p>Modern Frontend Development • React • TypeScript • Next.js</p>
              <p>Building scalable, high-performance web experiences with React & Next.js</p>
            </div>
            <a style={{ fontStyle: "italic" }} href="https://mohamed-jamal.netlify.app/" target="_blank" rel="noopener noreferrer">Visit My website</a>
          </center>
        </main>
      </div>
    </>
  );
}
